create table game (game_id varchar(255) not null, user_id varchar(255), winner varchar(255), primary key (game_id));
create table tennis_gem (gem_id varchar(255) not null, p1points varchar(255), p1tie varchar(255), p2points varchar(255), p2tie varchar(255), winner varchar(255), set_id varchar(255), primary key (gem_id));
create table tennis_set (set_id varchar(255) not null, winner varchar(255), game_id varchar(255), primary key (set_id));
alter table tennis_gem add constraint FK967if694kxkar15lljrddfk2l foreign key (set_id) references tennis_set (set_id);
alter table tennis_set add constraint FK514v9dpuc13r1mw85tun5lu9w foreign key (game_id) references game (game_id);
create table game (game_id varchar(255) not null, user_id varchar(255), winner varchar(255), primary key (game_id)) engine=InnoDB;
create table tennis_gem (gem_id varchar(255) not null, p1points varchar(255), p1tie varchar(255), p2points varchar(255), p2tie varchar(255), winner varchar(255), set_id varchar(255), primary key (gem_id)) engine=InnoDB;
create table tennis_set (set_id varchar(255) not null, winner varchar(255), game_id varchar(255), primary key (set_id)) engine=InnoDB;
alter table tennis_gem add constraint FK967if694kxkar15lljrddfk2l foreign key (set_id) references tennis_set (set_id);
alter table tennis_set add constraint FK514v9dpuc13r1mw85tun5lu9w foreign key (game_id) references game (game_id);
create table game (game_id varchar(255) not null, user_id varchar(255), winner varchar(255), primary key (game_id)) engine=InnoDB;
create table tennis_gem (gem_id varchar(255) not null, p1points varchar(255), p1tie varchar(255), p2points varchar(255), p2tie varchar(255), winner varchar(255), set_id varchar(255), primary key (gem_id)) engine=InnoDB;
create table tennis_set (set_id varchar(255) not null, winner varchar(255), game_id varchar(255), primary key (set_id)) engine=InnoDB;
alter table tennis_gem add constraint FK967if694kxkar15lljrddfk2l foreign key (set_id) references tennis_set (set_id);
alter table tennis_set add constraint FK514v9dpuc13r1mw85tun5lu9w foreign key (game_id) references game (game_id);
create table game (game_id varchar(255) not null, user_id varchar(255), winner varchar(255), primary key (game_id)) engine=InnoDB;
create table tennis_gem (gem_id varchar(255) not null, p1points varchar(255), p1tie varchar(255), p2points varchar(255), p2tie varchar(255), winner varchar(255), set_id varchar(255), primary key (gem_id)) engine=InnoDB;
create table tennis_set (set_id varchar(255) not null, winner varchar(255), game_id varchar(255), primary key (set_id)) engine=InnoDB;
alter table tennis_gem add constraint FK967if694kxkar15lljrddfk2l foreign key (set_id) references tennis_set (set_id);
alter table tennis_set add constraint FK514v9dpuc13r1mw85tun5lu9w foreign key (game_id) references game (game_id);
